### PR TITLE
Fix/added scheme free mario image url

### PR DESCRIPTION
**Pull request by ins0**
This PR

- [x] allow mario to show up on HTTP and HTTPS

### CODE REVIEW

**Comment by Ocramius** [comment]
@ins0 interesting, I really should just redirect non-https traffic though.

Merging for now, thanks!

**Comment by ins0** [comment]
my pleasure, but i'm not sure if forcing https is possible over github pages. thanks

**Comment by Ocramius** [comment]
> i'm not sure if forcing https is possible over github pages

Can do with a small JS snippet

**Comment by ins0** [comment]
sometimes i look for configuration files/keys and forget to think simple :cactus:

**Pull request merged**
